//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_FILEINTABLE
    {
        public decimal FILEINTABLEID { get; set; }
        public string TABLENAME { get; set; }
        public string FIELDNAME { get; set; }
        public decimal TABLEROWID { get; set; }
        public decimal ATTACHMENTID { get; set; }
    
        public virtual MT_Attachment MT_ATTACHMENT { get; set; }
    }
}
