//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_District
    {
        public MT_District()
        {
            this.Organization = new HashSet<MT_Organization>();
            this.ProjectOperations = new HashSet<ProjectOperation>();
            this.SubDistrict = new HashSet<MT_SubDistrict>();
            this.OrganizationRegisterEntries = new HashSet<OrganizationRegisterEntry>();
        }
    
        public decimal DistrictID { get; set; }
        public string DistrictName { get; set; }
        public decimal ProvinceID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<MT_Organization> Organization { get; set; }
        public virtual ICollection<ProjectOperation> ProjectOperations { get; set; }
        public virtual MT_Province Province { get; set; }
        public virtual ICollection<MT_SubDistrict> SubDistrict { get; set; }
        public virtual ICollection<OrganizationRegisterEntry> OrganizationRegisterEntries { get; set; }
    }
}
