//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTPROCESSED
    {
        public decimal PROCESSID { get; set; }
        public decimal PROJECTID { get; set; }
        public string ADDRESS { get; set; }
        public string BUILDING { get; set; }
        public string MOO { get; set; }
        public string SOI { get; set; }
        public string ROAD { get; set; }
        public Nullable<decimal> SUBDISTRICTID { get; set; }
        public string SUBDISTRICT { get; set; }
        public Nullable<decimal> DISTRICTID { get; set; }
        public string DISTRICT { get; set; }
        public decimal PROVINCEID { get; set; }
        public Nullable<decimal> LOCATIONMAPID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> PROCESSSTART { get; set; }
        public Nullable<System.DateTime> PROCESSEND { get; set; }
    }
}
