//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTQUESTION
    {
        public decimal QUESTTID { get; set; }
        public decimal QUESTHDID { get; set; }
        public string QTYPE { get; set; }
        public string QFIELD { get; set; }
        public string QVALUE { get; set; }
    
        public virtual PROJECTQUESTIONHD PROJECTQUESTIONHD { get; set; }
    }
}
