//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTBUDGETACTIVITY
    {
        public decimal ACTIVITYID { get; set; }
        public decimal PROJECTID { get; set; }
        public string ACTIVITYNAME { get; set; }
        public string ACTIVITYDESC { get; set; }
        public Nullable<long> RUNNO { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<decimal> CREATEBYID { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<decimal> UPDATEBYID { get; set; }
    }
}
