//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDocument
    {
        public decimal ProjectID { get; set; }
        public Nullable<decimal> DocumentID1 { get; set; }
        public Nullable<decimal> DocumentID2 { get; set; }
        public Nullable<decimal> DocumentID3 { get; set; }
        public Nullable<decimal> DocumentID4 { get; set; }
        public Nullable<decimal> DocumentID5 { get; set; }
        public Nullable<decimal> DocumentID6 { get; set; }
        public Nullable<decimal> DocumentID7 { get; set; }
        public Nullable<decimal> DocumentID8 { get; set; }
        public Nullable<decimal> DocumentID9 { get; set; }
        public Nullable<decimal> DocumentID10 { get; set; }
        public Nullable<decimal> DocumentID11 { get; set; }
        public Nullable<decimal> DocumentID12 { get; set; }
        public Nullable<decimal> DocumentID13 { get; set; }
        public Nullable<decimal> DocumentID14 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public decimal CreatedByID { get; set; }
        public Nullable<decimal> UpdatedByID { get; set; }
    
        public virtual ProjectGeneralInfo ProjectGeneralInfo { get; set; }
        public virtual MT_Attachment MT_Attachment1 { get; set; }
        public virtual MT_Attachment MT_Attachment10 { get; set; }
        public virtual MT_Attachment MT_Attachment11 { get; set; }
        public virtual MT_Attachment MT_Attachment12 { get; set; }
        public virtual MT_Attachment MT_Attachment13 { get; set; }
        public virtual MT_Attachment MT_Attachment14 { get; set; }
        public virtual MT_Attachment MT_Attachment2 { get; set; }
        public virtual MT_Attachment MT_Attachment3 { get; set; }
        public virtual MT_Attachment MT_Attachment4 { get; set; }
        public virtual MT_Attachment MT_Attachment5 { get; set; }
        public virtual MT_Attachment MT_Attachment6 { get; set; }
        public virtual MT_Attachment MT_Attachment7 { get; set; }
        public virtual MT_Attachment MT_Attachment8 { get; set; }
        public virtual MT_Attachment MT_Attachment9 { get; set; }
    }
}
