//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTHISTORY
    {
        public decimal HISTORYID { get; set; }
        public Nullable<decimal> PROJECTID { get; set; }
        public Nullable<System.DateTime> ENTRYDT { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string HISTORYTYPE { get; set; }
        public string IPADDRESS { get; set; }
    }
}
