//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFollowup
    {
        public decimal ProjectID { get; set; }
        public string ProjectName { get; set; }
        public decimal ProjectFollowUpValue { get; set; }
        public string Reason { get; set; }
        public decimal ReasonFollowUpValue { get; set; }
        public string Objective { get; set; }
        public decimal ObjectiveFollowUpValue { get; set; }
        public string TargetGroup { get; set; }
        public decimal TargetGroupFollowUpValue { get; set; }
        public string Location { get; set; }
        public decimal LocationFollowUpValue { get; set; }
        public string Timing { get; set; }
        public decimal TimingFollowUpValue { get; set; }
        public string OperationMethod { get; set; }
        public decimal OperationFollowUpValue { get; set; }
        public string Budget { get; set; }
        public decimal BudgetFollowUpValue { get; set; }
        public string Expectation { get; set; }
        public decimal ExpectationFollowUpValue { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public decimal CreatedByID { get; set; }
        public Nullable<decimal> UpdatedByID { get; set; }
    
        public virtual ProjectGeneralInfo ProjectGeneralInfo { get; set; }
    }
}
