//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPersonel
    {
        public decimal ProjectID { get; set; }
        public decimal Prefix1 { get; set; }
        public string Firstname1 { get; set; }
        public string Lastname1 { get; set; }
        public string Address1 { get; set; }
        public string Building1 { get; set; }
        public string Moo1 { get; set; }
        public string Soi1 { get; set; }
        public string Road1 { get; set; }
        public Nullable<decimal> SubDistrictID1 { get; set; }
        public string SubDistrict1 { get; set; }
        public Nullable<decimal> DistrictID1 { get; set; }
        public string District1 { get; set; }
        public decimal ProvinceID1 { get; set; }
        public string PostCode1 { get; set; }
        public string Telephone1 { get; set; }
        public string Fax1 { get; set; }
        public string Email1 { get; set; }
        public decimal Prefix2 { get; set; }
        public string Firstname2 { get; set; }
        public string Lastname2 { get; set; }
        public string Address2 { get; set; }
        public string Building2 { get; set; }
        public string Moo2 { get; set; }
        public string Soi2 { get; set; }
        public string Road2 { get; set; }
        public Nullable<decimal> SubDistrictID2 { get; set; }
        public string SubDistrict2 { get; set; }
        public Nullable<decimal> DistrictID2 { get; set; }
        public string District2 { get; set; }
        public decimal ProvinceID2 { get; set; }
        public string PostCode2 { get; set; }
        public string Telephone2 { get; set; }
        public string Fax2 { get; set; }
        public string Email2 { get; set; }
        public Nullable<decimal> Prefix3 { get; set; }
        public string Firstname3 { get; set; }
        public string Lastname3 { get; set; }
        public string Address3 { get; set; }
        public string Building3 { get; set; }
        public string Moo3 { get; set; }
        public string Soi3 { get; set; }
        public string Road3 { get; set; }
        public Nullable<decimal> SubDistrictID3 { get; set; }
        public string SubDistrict3 { get; set; }
        public Nullable<decimal> DistrictID3 { get; set; }
        public string District3 { get; set; }
        public Nullable<decimal> ProvinceID3 { get; set; }
        public string PostCode3 { get; set; }
        public string Telephone3 { get; set; }
        public string Fax3 { get; set; }
        public string Email3 { get; set; }
        public string SupportPlace1 { get; set; }
        public string SupportOrgName1 { get; set; }
        public Nullable<decimal> InstructorAmt2 { get; set; }
        public Nullable<decimal> InstructorListFileID2 { get; set; }
        public string SupportOrgName2 { get; set; }
        public Nullable<decimal> SupportBudgetAmt3 { get; set; }
        public string SupportOrgName3 { get; set; }
        public string SupportEquipment4 { get; set; }
        public string SupportOrgName4 { get; set; }
        public Nullable<decimal> SupportDrinkFoodAmt5 { get; set; }
        public string SupportOrgName5 { get; set; }
        public string SupportOrgName6 { get; set; }
        public Nullable<decimal> SupportValunteerAmt7 { get; set; }
        public Nullable<decimal> ValunteerListFileID7 { get; set; }
        public string SupportOrgName7 { get; set; }
        public string SupportOther8 { get; set; }
        public string SupportOrgName8 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> VehicleListFileID6 { get; set; }
        public string IDCardNo { get; set; }
        public string Mobile1 { get; set; }
        public decimal CreatedByID { get; set; }
        public Nullable<decimal> UpdatedByID { get; set; }
        public string OTHERPREFIX1 { get; set; }
        public string OTHERPREFIX2 { get; set; }
        public string OTHERPREFIX3 { get; set; }
    
        public virtual ProjectGeneralInfo ProjectGeneralInfo { get; set; }
        public virtual MT_ListOfValue Prefix1Personel { get; set; }
        public virtual MT_ListOfValue Prefix2Personel { get; set; }
        public virtual MT_ListOfValue Prefix3Personel { get; set; }
    }
}
