//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectBudget
    {
        public decimal ProjectBudgetID { get; set; }
        public decimal ProjectID { get; set; }
        public string BudgetDetail { get; set; }
        public decimal BudgetValue { get; set; }
        public string BudgetDetailRevise { get; set; }
        public decimal BudgetReviseValue { get; set; }
        public decimal BudgetReviseValue1 { get; set; }
        public decimal BudgetReviseValue2 { get; set; }
        public string RemarkRequest { get; set; }
        public string RemarkRevise { get; set; }
        public string RemarkApproval { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public decimal CreatedByID { get; set; }
        public Nullable<decimal> UpdatedByID { get; set; }
        public string BUDGETCODE { get; set; }
        public Nullable<decimal> ACTIVITYID { get; set; }
        public Nullable<decimal> ACTUALEXPENSE { get; set; }
    
        public virtual ProjectGeneralInfo ProjectGeneralInfo { get; set; }
    }
}
