//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCommittee
    {
        public decimal ProjectCommitteeID { get; set; }
        public decimal ProjectID { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string CommitteePosition { get; set; }
        public string Position { get; set; }
        public decimal OrderNo { get; set; }
        public string POSCODE { get; set; }
    
        public virtual ProjectGeneralInfo ProjectGeneralInfo { get; set; }
        public virtual K_MT_POSITION K_MT_POSITION { get; set; }
    }
}
