//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectApproval
    {
        public decimal ProjectID { get; set; }
        public decimal ApprovalStatusID1 { get; set; }
        public Nullable<decimal> ApprovalBudget1 { get; set; }
        public string ApprovalDesc1 { get; set; }
        public string ApprovalName1 { get; set; }
        public string ApprovalLastName1 { get; set; }
        public string ApproverPosition1 { get; set; }
        public Nullable<System.DateTime> ApprovalDate1 { get; set; }
        public Nullable<decimal> ApprovalStatusID2 { get; set; }
        public Nullable<decimal> ApprovalBudget2 { get; set; }
        public string ApprovalDesc2 { get; set; }
        public string ApprovalName2 { get; set; }
        public string ApprovalLastName2 { get; set; }
        public string ApproverPosition2 { get; set; }
        public Nullable<System.DateTime> ApprovalDate2 { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalNo { get; set; }
        public string ApprovalYear { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public decimal ApprovalBudgetTypeID { get; set; }
        public string ApprovalStatus { get; set; }
        public decimal CreatedByID { get; set; }
        public Nullable<decimal> UpdatedByID { get; set; }
    
        public virtual MT_ListOfValue ApprovalStatus1 { get; set; }
        public virtual MT_ListOfValue ApprovalStatus2 { get; set; }
        public virtual ProjectGeneralInfo ProjectGeneralInfo { get; set; }
        public virtual MT_ListOfValue ApprovalBudgetType { get; set; }
    }
}
