//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTDOCUMENTLIST
    {
        public decimal DOCID { get; set; }
        public decimal PROJECTID { get; set; }
        public decimal DOCUMENTNO { get; set; }
        public decimal DOCUMENTID { get; set; }
    
        public virtual MT_Attachment MT_ATTACHMENT { get; set; }
        public virtual ProjectGeneralInfo PROJECTGENERALINFO { get; set; }
    }
}
