//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_UserAccess
    {
        public string TicketID { get; set; }
        public decimal UserID { get; set; }
        public System.DateTime LastAccessTime { get; set; }
    
        public virtual SC_User User { get; set; }
    }
}
