//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegisterEntry
    {
        public UserRegisterEntry()
        {
            this.OrganizationRegisterEntries = new HashSet<OrganizationRegisterEntry>();
        }
    
        public decimal EntryID { get; set; }
        public Nullable<decimal> OrganizationID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string PersonalID { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public Nullable<decimal> PersonalIDCardAttachmentID { get; set; }
        public Nullable<decimal> EmployeeIDCardAttachmentID { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<decimal> RegisteredUserID { get; set; }
        public string Mobile { get; set; }
    
        public virtual MT_Attachment PersonalIDCardAttachment { get; set; }
        public virtual MT_Attachment EmployeeIDCardAttachment { get; set; }
        public virtual MT_Organization Organization { get; set; }
        public virtual SC_User RegisteredUser { get; set; }
        public virtual ICollection<OrganizationRegisterEntry> OrganizationRegisterEntries { get; set; }
    }
}
