//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.DBModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ParticipantProvinceDup
    {
        public decimal SectionID { get; set; }
        public string SectionName { get; set; }
        public decimal ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public decimal BudgetYear { get; set; }
        public string DisabilityTypeName { get; set; }
        public Nullable<decimal> CountParticipant { get; set; }
    }
}
