//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nep.Project.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nep.Project.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุการประเมิน {0}.
        /// </summary>
        public static string AssessmentRequiredField {
            get {
                return ResourceManager.GetString("AssessmentRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาให้คะแนน {0}.
        /// </summary>
        public static string AssessmentScoreRequiredField {
            get {
                return ResourceManager.GetString("AssessmentScoreRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านไม่สามารถเข้าถึงข้อมูลโครงการนี้.
        /// </summary>
        public static string CanotViewProjectData {
            get {
                return ResourceManager.GetString("CanotViewProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} มีค่าซ้ำ.
        /// </summary>
        public static string ClientDuplicateValue {
            get {
                return ResourceManager.GetString("ClientDuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุชื่อ-นามสกุล และตำแหน่ง.
        /// </summary>
        public static string CommitteeValidateEntryName {
            get {
                return ResourceManager.GetString("CommitteeValidateEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลโดยไม่เว้นแถวว่างระหว่างรายชื่อกรรมการหรือรายชื่อเจ้าหน้าที่.
        /// </summary>
        public static string CommitteeValidateSkip {
            get {
                return ResourceManager.GetString("CommitteeValidateSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ต้องเท่ากันกับ {1}.
        /// </summary>
        public static string CompareEqual {
            get {
                return ResourceManager.GetString("CompareEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านไม่ถูกต้อง.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถลบข้อมูลได้ เนื่องจากมีการใช้งานในระบบ.
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การลบไฟล์ไม่สำเร็จ กรุณาลองใหม่อีกครั้ง.
        /// </summary>
        public static string DeleteFileUnSuccess {
            get {
                return ResourceManager.GetString("DeleteFileUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} มีค่าซ้ำอยู่ในระบบ.
        /// </summary>
        public static string DuplicateValue {
            get {
                return ResourceManager.GetString("DuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบรูปแบบที่อยู่อีเมล์.
        /// </summary>
        public static string EmailField {
            get {
                return ResourceManager.GetString("EmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลมีการใช้งานแล้วในระบบ.
        /// </summary>
        public static string EmailRegistryDup {
            get {
                return ResourceManager.GetString("EmailRegistryDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} เกินเวลาที่กำหนด.
        /// </summary>
        public static string ExpiredValue {
            get {
                return ResourceManager.GetString("ExpiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์นี้ถูกเลือกแล้ว.
        /// </summary>
        public static string FileUploadDuplicate {
            get {
                return ResourceManager.GetString("FileUploadDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบอนุญาติให้แนบเอกสารที่มีนามสกุลดังนี้ {0}.
        /// </summary>
        public static string FileUploadExtensionInvalid {
            get {
                return ResourceManager.GetString("FileUploadExtensionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบไม่อนุญาติให้ Upload ไฟล์เกิน 8 Mb..
        /// </summary>
        public static string FileUploadMaximumExcess {
            get {
                return ResourceManager.GetString("FileUploadMaximumExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบรูปแบบวันที่.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่บัตรประชาชนไม่ถูกต้อง.
        /// </summary>
        public static string InvalidIDCardNo {
            get {
                return ResourceManager.GetString("InvalidIDCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านเดิมไม่ถูกต้อง กรุณาระบุใหม่.
        /// </summary>
        public static string InvalidOldPassword {
            get {
                return ResourceManager.GetString("InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง กรุณาระบุใหม่.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถ Reset Password ได้เนื่องจากยังไม่มี User Name.
        /// </summary>
        public static string ItemCannotResetPassword {
            get {
                return ResourceManager.GetString("ItemCannotResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ต้องน้อยกว่า {1}.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ต้องน้อยกว่าหรือเท่ากับ {1}.
        /// </summary>
        public static string LessThanOREqual {
            get {
                return ResourceManager.GetString("LessThanOREqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลการสมัคร.
        /// </summary>
        public static string NotFoundUserRegistry {
            get {
                return ResourceManager.GetString("NotFoundUserRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอก {0} เป็นตัวเลข.
        /// </summary>
        public static string NumberField {
            get {
                return ResourceManager.GetString("NumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อองค์กรมีในระบบแล้ว.
        /// </summary>
        public static string OrgNameRegistryDup {
            get {
                return ResourceManager.GetString("OrgNameRegistryDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีผู้ใช้องค์กรนี้ในระบบแล้ว.
        /// </summary>
        public static string OrgRegistryDup {
            get {
                return ResourceManager.GetString("OrgRegistryDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ต้องมากกว่า {1}.
        /// </summary>
        public static string OverThan {
            get {
                return ResourceManager.GetString("OverThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ต้องมากกว่าหรือเท่ากับ {1}.
        /// </summary>
        public static string OverThanOrEqual {
            get {
                return ResourceManager.GetString("OverThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปรษณีย์ไม่ถูกต้อง.
        /// </summary>
        public static string PostCodeField {
            get {
                return ResourceManager.GetString("PostCodeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การแก้ไขข้อมูลไม่ตอรงกับสถานะขั้นตอนการอนุมัติ.
        /// </summary>
        public static string ProjectApprovalStatusInvalid {
            get {
                return ResourceManager.GetString("ProjectApprovalStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลโครงการนี้ยังไม่ถูกต้อง.
        /// </summary>
        public static string ProjectInfoInvalid {
            get {
                return ResourceManager.GetString("ProjectInfoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผู้สมัครหมดอายุแล้ว กรุณาลงทะเบียนใหม่อีกครั้ง.
        /// </summary>
        public static string RegisterExpired {
            get {
                return ResourceManager.GetString("RegisterExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลการสมัคร.
        /// </summary>
        public static string RegisterNoFound {
            get {
                return ResourceManager.GetString("RegisterNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาแนบไฟล์  {0}.
        /// </summary>
        public static string RequiredAttachment {
            get {
                return ResourceManager.GetString("RequiredAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาแนบไฟล์อย่างน้อย 1 ไฟล์.
        /// </summary>
        public static string RequiredAttachmentOne {
            get {
                return ResourceManager.GetString("RequiredAttachmentOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุข้อมูล {0}.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกรายการ.
        /// </summary>
        public static string SelectItemError {
            get {
                return ResourceManager.GetString("SelectItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การส่งคำร้องเกิดข้อผิดพลาด กรุณาติดต่อผู้ดูแลระบบ.
        /// </summary>
        public static string SendDataToReviewUnsuccess {
            get {
                return ResourceManager.GetString("SendDataToReviewUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถส่ง SMS เนื่องจากเบอร์โทรศัพท์ไม่ถูต้อง.
        /// </summary>
        public static string SMSMobileInvalid {
            get {
                return ResourceManager.GetString("SMSMobileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอก {0} ไม่เกิน {1} ตัวอักษร.
        /// </summary>
        public static string StringLengthField {
            get {
                return ResourceManager.GetString("StringLengthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การแจ้งเตือนส่งรายงานโครงการขององค์กร{0}เกิดข้อผิดพลาด.
        /// </summary>
        public static string TrackingProjectReportError {
            get {
                return ResourceManager.GetString("TrackingProjectReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดปัญหาที่นอกเหนือความคาดหมาย กรุณาติดต่อผู้ดูแลระบบ.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้งานนี้ถูกระงับชั่วคราว กรุณาติดต่อผู้ดูแลระบบ.
        /// </summary>
        public static string UserInactiveError {
            get {
                return ResourceManager.GetString("UserInactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้งานหรือรหัสผ่านไม่ถูกต้อง กรุณาตรวจสอบชื่อผู้ใช้งานและรหัสผ่านอีกครั้ง.
        /// </summary>
        public static string UsernameOrPasswordMismatch {
            get {
                return ResourceManager.GetString("UsernameOrPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to องค์กรของท่านจัดตั้งไม่ถึง 6 เดือน.
        /// </summary>
        public static string ValicateOrgnizationRegisterDate {
            get {
                return ResourceManager.GetString("ValicateOrgnizationRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลรายละเอียดการใช้จ่าย.
        /// </summary>
        public static string ValidateApprovalBudgetDetail {
            get {
                return ResourceManager.GetString("ValidateApprovalBudgetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ ประธาน/นายก , กรรมการ และเจ้าหน้าที่ อย่างน้อยประเภทละ 1 คน.
        /// </summary>
        public static string ValidateCommitee {
            get {
                return ResourceManager.GetString("ValidateCommitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุเหตุผลเมื่อเลือก &quot;{0}&quot; เท่านั้น.
        /// </summary>
        public static string ValidateOperationLevelDesc {
            get {
                return ResourceManager.GetString("ValidateOperationLevelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดเงินรวมของรายการใช้จ่ายต้องเท่ากับยอดเงินรวมทั้งสิ้น.
        /// </summary>
        public static string ValidateProjectTotalBudgetAmount {
            get {
                return ResourceManager.GetString("ValidateProjectTotalBudgetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกจำนวนเงินของ {0} ให้เท่ากับจำนวนเงินเสนอขอ .
        /// </summary>
        public static string ValidateReviseBudgetAmount {
            get {
                return ResourceManager.GetString("ValidateReviseBudgetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกข้อมูลวงเงินสนับสนุน เมื่อมีการปรับลดงบประมาณเท่านั้น.
        /// </summary>
        public static string ValidateReviseBudgetApproval {
            get {
                return ResourceManager.GetString("ValidateReviseBudgetApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบอนุญาติให้สร้างประเภทผู้ใช้งานนี้เฉพาะส่วนกลางเท่านั้น.
        /// </summary>
        public static string ValidationAdministrator {
            get {
                return ResourceManager.GetString("ValidationAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} เป็นข้อมูลตัวเลขที่มีค่าระหว่าง {1} ถึง {2} .
        /// </summary>
        public static string ValidationRangeTypeNumber {
            get {
                return ResourceManager.GetString("ValidationRangeTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล {0} ไม่ถูกต้อง.
        /// </summary>
        public static string ValidationWrongFormat {
            get {
                return ResourceManager.GetString("ValidationWrongFormat", resourceCulture);
            }
        }
    }
}
