//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Nep.Project.Web.DesPersonWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="servicesSOAP", Namespace="http://110.78.8.36/ws")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getDesPersonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Nep.Project.Web.Properties.Settings.Default.Nep_Project_Web_DesPersonWS_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getDesPersonCompletedEventHandler getDesPersonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://110.78.8.36/ws/services.php", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDesPersonResponse", Namespace="http://110.78.8.36/ws")]
        public getDesPersonResponse getDesPerson([System.Xml.Serialization.XmlElementAttribute(Namespace="http://110.78.8.36/ws")] getDesPersonRequest getDesPersonRequest) {
            object[] results = this.Invoke("getDesPerson", new object[] {
                        getDesPersonRequest});
            return ((getDesPersonResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getDesPersonAsync(getDesPersonRequest getDesPersonRequest) {
            this.getDesPersonAsync(getDesPersonRequest, null);
        }
        
        /// <remarks/>
        public void getDesPersonAsync(getDesPersonRequest getDesPersonRequest, object userState) {
            if ((this.getDesPersonOperationCompleted == null)) {
                this.getDesPersonOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDesPersonOperationCompleted);
            }
            this.InvokeAsync("getDesPerson", new object[] {
                        getDesPersonRequest}, this.getDesPersonOperationCompleted, userState);
        }
        
        private void OngetDesPersonOperationCompleted(object arg) {
            if ((this.getDesPersonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDesPersonCompleted(this, new getDesPersonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://110.78.8.36/ws")]
    public partial class getDesPersonRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string person_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string person_code {
            get {
                return this.person_codeField;
            }
            set {
                this.person_codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://110.78.8.36/ws")]
    public partial class maimad {
        
        private string person_codeField;
        
        private string maimad_idField;
        
        private string first_name_thaiField;
        
        private string last_name_thaiField;
        
        private string sex_codeField;
        
        private string birth_dateField;
        
        private string deform_idField;
        
        private string deform_nameField;
        
        private string prefix_code_thaiField;
        
        private string prefix_name_abbrField;
        
        private string person_subtypeField;
        
        private string curator_idField;
        
        private string curr_address_noField;
        
        private string curr_address_nameField;
        
        private string curr_mooField;
        
        private string curr_soiField;
        
        private string curr_streetField;
        
        private string curr_sub_districtField;
        
        private string curr_subdistrict_nameField;
        
        private string curr_district_codeField;
        
        private string curr_district_nameField;
        
        private string curr_province_codeField;
        
        private string curr_province_nameField;
        
        private string home_region_codeField;
        
        private string home_region_nameField;
        
        private string home_postcodeField;
        
        private string home_telephoneField;
        
        private string home_faxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string person_code {
            get {
                return this.person_codeField;
            }
            set {
                this.person_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maimad_id {
            get {
                return this.maimad_idField;
            }
            set {
                this.maimad_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string first_name_thai {
            get {
                return this.first_name_thaiField;
            }
            set {
                this.first_name_thaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_name_thai {
            get {
                return this.last_name_thaiField;
            }
            set {
                this.last_name_thaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sex_code {
            get {
                return this.sex_codeField;
            }
            set {
                this.sex_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string birth_date {
            get {
                return this.birth_dateField;
            }
            set {
                this.birth_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deform_id {
            get {
                return this.deform_idField;
            }
            set {
                this.deform_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deform_name {
            get {
                return this.deform_nameField;
            }
            set {
                this.deform_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string prefix_code_thai {
            get {
                return this.prefix_code_thaiField;
            }
            set {
                this.prefix_code_thaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string prefix_name_abbr {
            get {
                return this.prefix_name_abbrField;
            }
            set {
                this.prefix_name_abbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string person_subtype {
            get {
                return this.person_subtypeField;
            }
            set {
                this.person_subtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curator_id {
            get {
                return this.curator_idField;
            }
            set {
                this.curator_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_address_no {
            get {
                return this.curr_address_noField;
            }
            set {
                this.curr_address_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_address_name {
            get {
                return this.curr_address_nameField;
            }
            set {
                this.curr_address_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_moo {
            get {
                return this.curr_mooField;
            }
            set {
                this.curr_mooField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_soi {
            get {
                return this.curr_soiField;
            }
            set {
                this.curr_soiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_street {
            get {
                return this.curr_streetField;
            }
            set {
                this.curr_streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_sub_district {
            get {
                return this.curr_sub_districtField;
            }
            set {
                this.curr_sub_districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_subdistrict_name {
            get {
                return this.curr_subdistrict_nameField;
            }
            set {
                this.curr_subdistrict_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_district_code {
            get {
                return this.curr_district_codeField;
            }
            set {
                this.curr_district_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_district_name {
            get {
                return this.curr_district_nameField;
            }
            set {
                this.curr_district_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_province_code {
            get {
                return this.curr_province_codeField;
            }
            set {
                this.curr_province_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curr_province_name {
            get {
                return this.curr_province_nameField;
            }
            set {
                this.curr_province_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string home_region_code {
            get {
                return this.home_region_codeField;
            }
            set {
                this.home_region_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string home_region_name {
            get {
                return this.home_region_nameField;
            }
            set {
                this.home_region_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string home_postcode {
            get {
                return this.home_postcodeField;
            }
            set {
                this.home_postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string home_telephone {
            get {
                return this.home_telephoneField;
            }
            set {
                this.home_telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string home_fax {
            get {
                return this.home_faxField;
            }
            set {
                this.home_faxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://110.78.8.36/ws")]
    public partial class getDesPersonResponse {
        
        private string return_codeField;
        
        private string return_messageField;
        
        private maimad[] maimad_detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string return_code {
            get {
                return this.return_codeField;
            }
            set {
                this.return_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string return_message {
            get {
                return this.return_messageField;
            }
            set {
                this.return_messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public maimad[] maimad_details {
            get {
                return this.maimad_detailsField;
            }
            set {
                this.maimad_detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getDesPersonCompletedEventHandler(object sender, getDesPersonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDesPersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDesPersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getDesPersonResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getDesPersonResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591